addons:
  sonarcloud:
    organization: "leila-devrap"
    token:
      secure: "af9dc25d239aa82a8375a5369c18ed02a9b05ad2" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Leila-DevRap_formationjava